version: "3.9"

services:
  zipkin:
    image: openzipkin/zipkin
    restart: always
    ports:
      - 7001:9411

  db:
    image: mongo:4.4.6
    restart: always
    ports:
      - 6001:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: db-user
      MONGO_INITDB_ROOT_PASSWORD: db-password

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5001:15672
      - 5002:5672
