server:
  port: 9002

eureka:
  client:
    enabled: false

spring:
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: localhost
      port: 6002
      username: db-user
      password: db-password
      database: task-db

  zipkin:
    base-url: http://localhost:7001/

  rabbitmq:
    addresses: localhost:5002
