spring:
  application:
    name: project-service

  profiles:
    active: ${ACTIVE_PROFILE}

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

custom:
  firebase:
    credentials: ${FIREBASE_CREDENTIALS}

  rabbitmq:
    project-save-queue: project-save-queue
    project-delete-queue: project-delete-queue
    project-save-binding: project-save-binding
    project-delete-binding: project-delete-binding
    exchange: exchange
