name: project service test

on:
  pull_request:
    branches:
      - main
      - qa
    paths:
      - project-service/**

defaults:
  run:
    working-directory: project-service

jobs:
  project-service-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: setup jdk 16
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "adopt"

      - name: run tests
        run: ./mvnw --batch-mode test

      - name: generate reports
        if: always()
        run: |
          ./mvnw site -DgenerateReports=false
          ./mvnw surefire-report:report-only

      - name: upload reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: |
            project-service/target/surefire-reports
            project-service/target/site
          name: project-service-reports
