name: service gateway prod deploy

on:
  push:
    branches:
      - main
    paths:
      - service-gateway/**

jobs:
  service-gateway-prod-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: timely-service-gateway11
          heroku_email: ${{ secrets.HEROKU_USER }}
          appdir: service-gateway
