name: task service deploy

on:
  push:
    branches:
      - main
    paths:
      - task-service/**

jobs:
  task-service-prod-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: timely-task-service11
          heroku_email: ${{ secrets.HEROKU_USER }}
          appdir: task-service
          healthcheck: https://timely-task-service11.herokuapp.com/ping
          checkstring: pong from task-service
